-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 23:34:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema popeyeDB
-- -----------------------------------------------------
-- Base de datos de tienda popeye

-- -----------------------------------------------------
-- Schema popeyeDB
--
-- Base de datos de tienda popeye
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `popeyeDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `popeyeDB` ;

-- -----------------------------------------------------
-- Table `popeyeDB`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `popeyeDB`.`categoria` (
  `CATEGORIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA` VARCHAR(60) NOT NULL,
  `ESTADO` CHAR(1) NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `FECHA_ACTUALIZACION` DATETIME NOT NULL,
  PRIMARY KEY (`CATEGORIA_ID`),
  UNIQUE INDEX `clasificacion_id_UNIQUE` (`CATEGORIA_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popeyeDB`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `popeyeDB`.`producto` (
  `PRODUCTO_ID` BINARY(16) NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `PRECIO` DECIMAL(4,2) NOT NULL,
  `CODIGO_BARRAS` CHAR(1) NULL,
  `ESTADO` CHAR(1) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `FECHA_ACTUALIZACION` DATETIME NOT NULL,
  `PK_CATEGORIA` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_ID`),
  INDEX `fk_producto_categoria_idx` (`PK_CATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`PK_CATEGORIA`)
    REFERENCES `popeyeDB`.`categoria` (`CATEGORIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
